### ISSUE TITLE
Read and use system networking properties

### ISSUE THREAD

**Issue by mwnu** [mszpro/Nil#1]

**Comment by mszpro** [comment]
Thank you for your report!

Could you share some screenshots or the text of the error message?

Also, which login method are yo using? Passwords or QR codes?

Thank you!

@mwnu

**Comment by mwnu** [comment]
> Thank you for your report!
> 
> Could you share some screenshots or the text of the error message?
> 
> Also, which login method are yo using? Passwords or QR codes?
> 
> Thank you!
> 
> @mwnu

Sorry, it seems to be a network issue. After I re-downloaded the app, I was able to log in. Then, I experienced several failed session verifications, probably due to the delay caused by syncing a large number of room messages.

**Comment by mwnu** [comment]
Additionally, my iPad's performance is insufficient to run a local AI model. Supporting a cloud-based AI API (such as OpenAI) would be a great alternative.

**Comment by mszpro** [comment]
Got it! Thank you for your reply! @mwnu 

I also discovered an issue that the app does not work very well when some system networking properties are changed.
I will fix this issue.

Also, I will consider adding an online AI API (Gemini).

I will mention you when the changes are implemented.

Please feel free to continue to report any issues and feedbacks.

Best,
Developer
