### ISSUE TITLE
Search could not find contents (even those in visible rooms list) on self hosted server

### ISSUE THREAD

**Issue by ajkessel** [mszpro/Nil#2]
Search always returns no results for me. Using the latest release from the App Store with my own homeserver. Rooms are all visible and I can interact fine, but search results always just look like this:

![image](https://github.com/mszpro/Nil/assets/3332524/0de8437d-19c0-4a25-a808-076885cff209)

**Comment by mszpro** [comment]
Thanks for your feedback! @ajkessel 

I will look into this, and let you know when there's any progress.

Best,
Developer

**Comment by ajkessel** [comment]
To clarify, it's not just contacts--it finds nothing. I can't find rooms, contacts, or messages.

**Comment by mszpro** [comment]
Got it @ajkessel

**Comment by ajkessel** [comment]
Also, the tip says "hit return to perform online search", but my understanding is Nil can search locally (i.e. included encrypted rooms), right?

**Comment by ajkessel** [comment]
Not sure if you fixed something in the code or if it just took time to index the content, but search is now returning results as expected.

**Comment by mszpro** [comment]
Thanks for confirming the fix! 

Yes I implemented a new logic for search in the most recent update V1.2. 

Closing this issue now! Let me know if there is any issues or feedbacks at any time.

@ajkessel
